apiVersion: batch/v1
kind: Job
metadata:
  name: cook-lambda-{{RANDOM}}  # <== Replaced by a random string to provide always uniq Jobs (lambdas)
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: cook
        image: petrificustotalus/cook-gitfaas-demo:0.0.1
        env:
        - name: PAYLOAD
          value: "{{PAYLOAD}}"        # <== Replaced by the message sent to this lambda
        - name: FUNCTION_UID
          value: "{{FUNCTION_UID}}"   # <== Replaced by a uniq UID used to post the lambdas response back to Gitfaas
      restartPolicy: Never
      imagePullPolicy: Always
